  const PREFIX = 'user'
  export const GET_USERS_PENDING = `${PREFIX}/GET_USERS_PENDING`
  export const GET_USERS_FULLFILLED = `${PREFIX}/GET_USERS_FULLFILLED`
  export const GET_USERS_REJECTED = `${PREFIX}/GET_USERS_REJECTED`
  export const GET_USER_DETAIL = `${PREFIX}/GET_USER_DETAIL`
  export const SEARCH_USER = `${PREFIX}/SEARCH_USER`